Lab3
alexrush1/network_labs pull request #4
Opened 2020-11-09 07:16 UTC by alexrush1

@Aloomenon 
System.out.println("Hello, world!");

2020-11-10 16:51 UTC, alexrush1 commented
ping @Aloomenon

2020-11-13 08:39 UTC, alexrush1 commented
@Aloomenon доброй день!

2020-11-14 09:28 UTC, Aloomenon requested changes

2020-11-14 09:28 UTC, Aloomenon commented on Lab3/treechat/model/transfer/Receiver.java
> +            } else if (message.getMessageType() == MessageType.WELCOME) {
Ну зочем

2020-11-14 09:28 UTC, Aloomenon commented on Lab3/treechat/model/transfer/Receiver.java
> +            Message message = (Message) BytesConverter.getObject(packet.getData());
кодировка какая?

2020-11-14 09:55 UTC, alexrush1 commented on Lab3/treechat/model/transfer/Receiver.java
> +            Message message = (Message) BytesConverter.getObject(packet.getData());
походу та, которая по умолчанию стоит. Использовав Charset.defaultCharset() увидел, что это UTF-8

2020-11-14 09:55 UTC, alexrush1 commented on Lab3/treechat/model/transfer/Receiver.java
> +            } else if (message.getMessageType() == MessageType.WELCOME) {
:D

2020-11-14 12:52 UTC, alexrush1 commented on Lab3/treechat/model/transfer/Receiver.java
> +            Message message = (Message) BytesConverter.getObject(packet.getData());
@Aloomenon Пингую просто потому что не знаю, видите ли вы о том, что я что-то написал или нет

2020-11-15 21:10 UTC, Aloomenon commented
ок, принял. Но в дальнейшем еще и кодировку надо писать, а то вдруг вам с cp1251 идут сообщения.

2020-11-15 21:11 UTC, alexrush1 commented
Ок, вас понял, спасибо!

2020-11-16 01:40 UTC, merged